feat(mobile): criação do componente de input
diego3g/rsxp-2023 pull request #100
Opened 2023-04-11 18:56 UTC by melquisedeque-magalhaes

# 📋 Descrição

criação do componente de input

## 🛠️ Tipo da mudança

Exclua as opções que não são relevantes.

![Capturar_select-area_20230411155412](https://user-images.githubusercontent.com/43079783/231261839-93d5bd27-49f5-4b15-9d38-aa738035e560.png)

- [x] Nova feature

# 📷 Screenshots

Exclua essa sessão caso não seja relevante.

- Antes:

- Depois:

# ✅ Checklist:

- [x] O título do meu PR está seguindo o padrão `<type>(scope): subject`. Por exemplo: `feat(mobile): add new feature`
- [x] Meu código segue as diretrizes de estilo deste projeto
- [x] Realizei uma auto revisão do meu código
- [x] Fiz alterações correspondentes na documentação
- [x] Minhas alterações não geram novos alertas
- [x] Adicionei testes para minhas alterações

2023-04-11 19:14 UTC, diego3g requested changes

2023-04-11 19:14 UTC, diego3g commented on apps/mobile/src/components/Input.tsx
> +}
Prefiro que sigamos o mesmo padrão do `Button` tendo:
```jsx
<Input.Root>
  <Input.Icon>
    <Hash size={20} color={theme?.colors?.gray[400]} />
  </Input.Icon>
  <Input.Control />
</Input.Root>
```

Até no botão acho que faltou ter um `<Button.Icon />`

2023-04-11 19:14 UTC, diego3g commented on apps/mobile/src/components/Input.tsx
> +            'ml-2': icon,
Acho que tu pode usar o `gap-x-2` na `View` ao invés desse `margin`

2023-04-11 20:07 UTC, melquisedeque-magalhaes commented on apps/mobile/src/components/Input.tsx
> +}
mas @diego3g no icone a estilização vai toda para o próprio icone, sera que faz sentindo ter o `Input.Icon` ?

2023-04-11 20:07 UTC, melquisedeque-magalhaes commented on apps/mobile/src/components/Input.tsx
> +            'ml-2': icon,
booooa :rocket:

2023-04-11 20:15 UTC, melquisedeque-magalhaes commented on apps/mobile/src/components/Input.tsx
> +}
![Uploading Capturar_select-area_20230411171548.png…]()

2023-04-11 20:16 UTC, melquisedeque-magalhaes commented on apps/mobile/src/components/Input.tsx
> +}
![image](https://user-images.githubusercontent.com/43079783/231278453-f555a227-0160-4f39-b1fd-a0abc95a491b.png)

2023-04-11 20:22 UTC, melquisedeque-magalhaes commented on apps/mobile/src/components/Input.tsx
> +            'ml-2': icon,
Colocando essa propriedade na View por algum motivo ele afeta o componente por fora e não internamente, olha como ele desalinhou os items

![Capturar_select-area_20230411172118](https://user-images.githubusercontent.com/43079783/231279406-cf3275d5-6048-46a6-8f62-df2794cf57d6.png)

2023-04-11 20:29 UTC, melquisedeque-magalhaes commented on apps/mobile/src/components/Input.tsx
> +}
Boooa @diego3g  ajustei aqui ficou melhor mesmo :rocket:

2023-04-12 10:55 UTC, melquisedeque-magalhaes commented on apps/mobile/src/components/Input.tsx
> +            'ml-2': icon,
![Screenshot_2023-04-12-07-55-13-155_com.android.chrome.jpg](https://user-images.githubusercontent.com/43079783/231437105-934a5dee-a652-4f8e-b490-1cfa289a19a2.jpg)

2023-04-12 15:57 UTC, merged