[0009] Layout do cabeçalho e menu em abas
diego3g/rsxp-2023 pull request #77
Opened 2023-04-06 13:41 UTC by RennanD

# 📋 Descrição

Essa PR finaliza o que o @rodrigorgtic criou, com o Drawer e cria o header tanto das telas do Tab Navigation, quanto das telas de Drawer.
Ela também remove as tela de navegação em pilha.

Fixes #67

## 🛠️ Tipo da mudança

Exclua as opções que não são relevantes.

- [x] Nova feature

# 📷 Screenshots

![Captura de Tela 2023-04-06 às 10 39 07](https://user-images.githubusercontent.com/15038553/230395390-14842184-efe4-4b61-a985-12d77424f1f3.png)

# ✅ Checklist:

- [x] Meu código segue as diretrizes de estilo deste projeto
- [x] Realizei uma auto revisão do meu código
- [x] Minhas alterações não geram novos alertas

2023-04-06 13:48 UTC, diego3g commented
Fala @RennanD, pela print parece que as abas não estão seguindo o espaçamento interno vertical de 16px, confere? Vale dar um double check no layout do Figma pra ver se tudo está 100% <3 
![CleanShot 2023-04-06 at 10 47 52](https://user-images.githubusercontent.com/2254731/230397712-b7ff7dc6-ed1b-4633-87c4-39fa3a44d80a.png)

2023-04-06 13:55 UTC, diego3g requested changes

2023-04-06 13:55 UTC, diego3g commented on apps/mobile/app/(drawer)/(tabs)/_layout.tsx
> +import { TabsHeader } from '../../components/TabsHeader'
Podemos usar a config de path alias?
```suggestion
import { TabsHeader } from '@/components/TabsHeader'
```

2023-04-06 13:55 UTC, diego3g commented on apps/mobile/app/assets/rsxp-logo.svg
Parece que o logo aqui está com uma sombra, talvez seja legal exportar sem a sombra...

2023-04-06 15:56 UTC, RennanD commented
> Fala @RennanD, pela print parece que as abas não estão seguindo o espaçamento interno vertical de 16px, confere? Vale dar um double check no layout do Figma pra ver se tudo está 100% <3
> 
> ![CleanShot 2023-04-06 at 10 47 52](https://user-images.githubusercontent.com/2254731/230397712-b7ff7dc6-ed1b-4633-87c4-39fa3a44d80a.png)
> 
> Fora isso, a cor também não está batendo totalmente, acredito que seja pela falta do merge da PR #71 certo?!

Em relação as cores é isso mesmo, pelo menos  cor de ícone ativo e inativo está assim por conta dos tokens de cor não estarem configurados.

Posso abrir uma issue para alterar essas cores após a #71  ser aprovada, o que achas?

2023-04-06 15:57 UTC, RennanD commented on apps/mobile/app/assets/back-icon.svg
Podemos sim, vou fazer essa alteração!!

2023-04-06 15:57 UTC, RennanD commented on apps/mobile/app/assets/rsxp-logo.svg
Beleza amigo, vou conferir o motivo de ter ficado com essa sombra. 💜

2023-04-06 17:15 UTC, LuizHAP commented on apps/mobile/app/(drawer)/(tabs)/_layout.tsx
> +import { TabsHeader } from '../../components/TabsHeader'
eu tentei também utilizar na #79 e quebrou várias coisas do expo. Será que precisamos fazer alguma configuração específica? Minha suposição é alguma coisa com o expo-router

2023-04-06 18:04 UTC, diego3g commented
@RennanD #71 entrou :)

2023-04-06 18:11 UTC, RennanD commented on apps/mobile/app/(drawer)/(tabs)/_layout.tsx
> +import { TabsHeader } from '../../components/TabsHeader'
@diego3g  sobre o alias, não consegui resolver. 😕
Ao que parece o babel resolver não está entendendo a pasta `app` como diretório root, talvez o @rodrigorgtic saiba como resolver isso e possamos abrir uma issue para corrigir esse path mapping, o que achas?

2023-04-06 18:12 UTC, RennanD commented
> @RennanD #71 entrou :)

Shoow!! Já vou usar as cores certas. 💜

2023-04-06 18:32 UTC, RennanD commented on apps/mobile/app/(drawer)/(tabs)/_layout.tsx
> +import { TabsHeader } from '../../components/TabsHeader'
@LuizHAP provavelmente seja algo do próprio plugin do module resolver mesmo. 😕

2023-04-06 18:55 UTC, RennanD commented
> @RennanD #71 entrou :)

amigo , percebi que utilizando as cores no dentro do `extends` no `tailwind.config.js` só funciona para as classes, então quando utilizo dentro das opções do TabBar, para as labels por exemplo, acaba ficando com o token padrão do Tailwind.

Vou mover essas cores para a raiz do tema, já que só elas vão ser utilizadas no app, beleza?

2023-04-06 19:08 UTC, diego3g commented
@RennanD Acho que precisa usar o resolveConfig: https://tailwindcss.com/docs/configuration#referencing-in-java-script

2023-04-06 20:08 UTC, RennanD commented
@diego3g confere se tá tudo certinho agora. 💜

2023-04-06 20:40 UTC, diego3g requested changes

2023-04-06 20:40 UTC, diego3g commented on apps/mobile/app/components/DrawerHeader.tsx
> +  const insents = useSafeAreaInsets()
Aqui está escrito `insets` errado.

2023-04-06 20:40 UTC, diego3g commented on apps/mobile/app/components/DrawerItem.tsx
> +import colors from 'tailwindcss/colors'
Acho que aqui poderia usar o theme também.

2023-04-06 20:40 UTC, diego3g commented
@RennanD dois últimos ajustes e se puder colocar uma print de como ficou seria massa! :)

2023-04-06 20:52 UTC, RennanD commented on apps/mobile/app/components/DrawerHeader.tsx
> +  const insents = useSafeAreaInsets()
Show, vou ajustar!!

2023-04-06 20:53 UTC, RennanD commented on apps/mobile/app/components/DrawerItem.tsx
> +import colors from 'tailwindcss/colors'
Verdade amigo, acabou passando sem eu ver.
Valeu pelo feedback.💜

2023-04-06 20:57 UTC, RennanD commented
@RennanD tranquilo amigo, o print acha melhor colocar como um comentário aqui mesmo?

2023-04-06 21:13 UTC, diego3g commented
@RennanD sim

2023-04-06 21:35 UTC, melquisedeque-magalhaes commented
> > @RennanD #71 entrou :)
> 
> amigo , percebi que utilizando as cores no dentro do `extends` no `tailwind.config.js` só funciona para as classes, então quando utilizo dentro das opções do TabBar, para as labels por exemplo, acaba ficando com o token padrão do Tailwind.
> 
> Vou mover essas cores para a raiz do tema, já que só elas vão ser utilizadas no app, beleza?

mano na Pr #81 eu fiz uma forma de utilizar as cores fora das classe se quiser dar uma olhada mano, acho que e uma abordagem interessante.

2023-04-06 21:55 UTC, diego3g commented
@melquisedeque-magalhaes acho que como o @RennanD fez é melhor, com o resolveConfig, inclusive é o recomendado na doc do tailwind.

2023-04-06 22:01 UTC, melquisedeque-magalhaes commented
> @melquisedeque-magalhaes acho que como o @RennanD fez é melhor, com o resolveConfig, inclusive é o recomendado na doc do tailwind.

shooow @diego3g  e @RennanD gostei da implementação do resolveConfig também muito massa, quando der o merge nessa Pr vou atualizar a minha.

2023-04-07 13:01 UTC, RennanD commented
@diego3g acho que agora foi huheuhe!! Além do que tinha pedido para ajustar, refatorei para utilizar os path e ficou muito melhor.

![Captura de Tela 2023-04-07 às 09 41 12](https://user-images.githubusercontent.com/15038553/230613090-18502b55-a88c-44b4-814d-fb4c25bb99d2.png)

2023-04-07 13:55 UTC, hnqg commented
Pessoal, o CI foi atualizado então vcs vão ver que já tem alguns jobs falhando. 

Pra o o job do `Semantic PR Titles` passar vcs tem que escrever o título no formato do conventional commits (só add um `feat(mobile): `) na frente já resolve.

Sobre o de types checking, podem ignorar por enquanto pois é um erro de node_modules que está em resolução

vlww 👊

2023-04-07 14:38 UTC, diego3g commented
@RennanD No layout eu coloquei o padding das tabs abaixo maior porque é iOS e tem o notch, mas no Android deveria ficar igual.

2023-04-07 19:28 UTC, LucasCarrias commented on apps/mobile/app/(drawer)/(tabs)/_layout.tsx
> +import { TabsHeader } from '../../components/TabsHeader'
Acredito que algumas incosistências do module resolver sejam por causa que quando o ele foi configurado foi levado em conta que a raiz da aplicação seria o `./src`. No entanto, algumas dependências estão sendo criadas simultaneamentes na `app` e `src`. Até isso ser padroniziado, imagino que seja melhor seguir como o @LuizHAP fez abaixo:

https://github.com/diego3g/rsxp-2023/blob/main/apps/mobile/babel.config.js#L21-L24

2023-04-10 12:36 UTC, RennanD commented
Fala @diego3g , fiz uma condição para verificar o `Inset Bottom` e aplicar uma altura e um `Padding bottom` diferentes par o ios no caso do notch.

![Captura de Tela 2023-04-10 às 09 25 23](https://user-images.githubusercontent.com/15038553/230902508-7a39ab98-fded-494f-8e95-51eeac81f342.png)

2023-04-10 12:37 UTC, merged