feat: add Sympla service
diego3g/rsxp-2023 pull request #78
Opened 2023-04-06 13:56 UTC by gabe-frasz

# 📋 Descrição

Criei o serviço de comunicação com a API do Sympla com um único método que retorna as informações do participante de acordo com o número do ingresso. Para isso, instalei e configurei o `axios` e adicionei duas novas variáveis ambiente (definidas no `.env.example`). Por fim, incluí o serviço do Sympla no `app.module.ts`.

Também adicionei a tipagem da resposta da API com os campos que achei mais relevante, mas vou deixar essa parte e a possibilidade de adicionar novos métodos em aberto e sujeitos à mudança por enquanto.

Fixes #65 

## 🛠️ Tipo da mudança

- [x] Nova feature

# 🧪 Como isso foi testado?

Realizei testes manuais.

- Criei um evento teste na minha conta do Sympla e coloquei o ID na respectiva variável ambiente
- Adicionei uma rota temporária no `app.controller.ts` que retornava a resposta do único método do serviço até então

# ✅ Checklist:

- [x] Meu código segue as diretrizes de estilo deste projeto
- [x] Realizei uma auto revisão do meu código
- [ ] Fiz alterações correspondentes na documentação
- [ ] Minhas alterações não geram novos alertas
- [ ] Adicionei testes para minhas alterações

2023-04-06 15:32 UTC, jorge-lba commented
@gabe-frasz seria legal ver com o @diego3g se não seria dar um nome diferente como em vez de service usar provider. 
Falo isso pq o nest utiliza service para adicionar lógicas de negócio ( parecido com o use case da arquitetura limpa ) e acho que isso pode confundir o pessoal por termos dois dermos iguais para funcionalidades diferentes

2023-04-06 15:47 UTC, gabe-frasz commented
> @gabe-frasz seria legal ver com o @diego3g se não seria dar um nome diferente como em vez de service usar provider.
> 
> Falo isso pq o nest utiliza service para adicionar lógicas de negócio ( parecido com o use case da arquitetura limpa ) e acho que isso pode confundir o pessoal, por utilizar dois termos iguais para finalidades diferentes

Certo, vamos aguardar a resposta dele.

E sobre a funcionalidade em si, você acredita que haja a necessidade de adicionar um novo método que possa ser necessário no futuro?

2023-04-06 17:12 UTC, LuizHAP commented on apps/server/src/sympla/sympla.service.ts
> +  }
usar um try/catch ficaria melhor? Nunca trabalhei com Nest, então fiquei na dúvida

2023-04-06 18:01 UTC, jorge-lba commented on apps/server/src/sympla/sympla.service.ts
> +  }
Se formos levar em conta que o Diego quero manter o código mais simples acredito que o trycatch seria uma boa opção, só um ponto é que o nest tem seus erro padrões e acho que poderíamos usar eles.

Uma unica coisa que eu faria um pouco diferente, seria retornar o erro e tratar ele no controller, mas isso é uma preferencia. Podemos ver de criar uma discussão para determinar onde seria o local padrão para tratar erros.

2023-04-06 18:03 UTC, jorge-lba commented
@gabe-frasz acredito que para cada item da lista que temos de back so sympla seria uma função no service( ou provider heheh )

2023-04-06 18:04 UTC, jorge-lba commented on apps/server/src/sympla/sympla.service.ts
> +  }
aqui está o link da doc para se vc quiser entender melhor como funciona [Execptions](https://docs.nestjs.com/exception-filters)

2023-04-07 17:46 UTC, eletroswing commented
@gabe-frasz  se ajudar, aqui está um pull que eu ia fazer mais cedo, por não ter visto este. Se conseguir tirar algo para ajudar.. [Pull request 87.](https://github.com/diego3g/rsxp-2023/pull/87)

2023-04-07 18:41 UTC, eletroswing commented on apps/server/src/sympla/sympla.service.ts
> +  }
uma forma que eu encontrei, foi verificar se o objeto retornado do data.data não está vazio, adicionando a clausula ao 'return': `return Object.keys(response.data.data).length === 0
      ? undefined
      : response.data.data`. Assim simplesmente verificando a resposta se é "undefined" sabemos se tem um erro na requisição ou não, ou então, simplesmente lançamos um erro

2023-04-10 17:04 UTC, gabe-frasz commented
Boa tarde, pessoal. Fiz algumas pequenas alterações de acordo com os feedbacks.

- Coloquei a resposta da API em um arquivo separado
- Adicionei o try/catch e, caso haja erro, ele é retornado pelo serviço ao invés dos dados do participante

2023-04-10 18:15 UTC, diego3g requested changes

2023-04-10 18:15 UTC, diego3g commented on apps/server/src/lib/axios.ts
> +export const symplaApi = axios.create({
Eu instanciaria isso direto dentro do service do sympla no construtor e não num arquivo separado porque mais pra frente poderemos ter mais conexões com outras APIs ainda utilizando o axios e esse arquivo ficaria estranho.

2023-04-10 18:15 UTC, diego3g commented on apps/server/src/sympla/sympla.service.ts
> +      )
E se ao invés de colocar os tipos em um arquivo separado a gente utilizasse o Zod pra validar o retorno da API e fazer a inferência de tipos de forma automática? 
```ts
@Injectable()
export class SymplaService {
  private symplaAPIClient: AxiosInstance

  constructor() {
    this.symplaAPIClient = axios.create({ 
      // ... axios config stuff
    })
  }

  public async getParticipantByTicketNumber(ticketNumber: number) {
    try {
      const { data } = await this.symplaAPIClient.get(
        `/events/${process.env.SYMPLA_EVENT_ID}/participants/ticketNumber/${ticketNumber}`,
      )

      const ticketSchema = z.object({
        id: z.number(),
        order_id: z.string(),
        order_status: z.string(),
        order_date: z.string(),
        first_name: z.string(),
        last_name: z.string(),
        email: z.string().email(),
        ticket_number: z.string(),
        ticket_num_qr_code: z.string(),
      })

      return ticketSchema.parse(data.data)
    } catch (error) {
      return error.response.data as ParticipantResponseError
    }
  }
}
```

2023-04-10 18:50 UTC, gabe-frasz commented on apps/server/src/sympla/sympla.service.ts
> +      )
Só uma dúvida: Para manter a coerência das nomenclaturas, o retorno desse método será tratado como `ticket` ou `participant`?

Na documentação da API, esse endpoint retorna "o participante correspondente ao ingresso informado".

2023-04-10 18:59 UTC, diego3g commented on apps/server/src/sympla/sympla.service.ts
> +      )
Ah, pode ser participant, eu nem olhei pra doc da API

2023-04-10 19:52 UTC, diego3g approved these changes

2023-04-10 19:53 UTC, diego3g commented
@gabe-frasz podes resolver os conflitos? Do `package-lock.json` é só apagar o arquivo e rodar um `npm install` do zero.

2023-04-10 21:05 UTC, gabe-frasz commented
Resolvidos! 💪

2023-04-10 23:13 UTC, diego3g commented
tem um pouquinho mais @gabe-frasz

2023-04-11 00:26 UTC, merged