feat(server): adicionando auth guard para o backend com validação do clerk
diego3g/rsxp-2023 pull request #99
Opened 2023-04-11 12:25 UTC by eletroswing

# 📋 Descrição

Este commit trás a implementação do AuthGuard com validação do Clerk, para evitar furos de segurança na aplicação.

Foram criados 3 arquivos: 
--> **clerk.service:** o serviço que interage diretamente com a api do Clerk, para validar o token jwt enviado
--> **clerk.guard:** o guarda que verifica se um `bearer token` foi enviado no header da apliação, valida o mesmo, e gera os erros ou adiciona ao contexto da requisição o cliente associado ao token
--> **requestInterface**: a interface que faz a junção do Request com a interface do cliente vindo do guarda

Foi adicionado uma nova rota a base da aplicação(`/test-clerk-auth-guard` ) com o fim de demonstrar como o guarda é, e pode ser utilizado para o desenvolvimento

## 🛠️ Tipo da mudança

- [x] Nova feature: autenticação na api

# 🧪 Como isso foi testado?

Foi criado uma aplicação de testes no Clerk, e adicionado a variável de ambiente o token da api. O jwt de um úsuario(salvo no local storage) foi o token ultilizado para acessar a rota.

# ✅ Checklist:

- [x] O título do meu PR está seguindo o padrão `<type>(scope): subject`. Por exemplo: `feat(mobile): add new feature`
- [x] Meu código segue as diretrizes de estilo deste projeto
- [x] Realizei uma auto revisão do meu código
- [x] Fiz alterações correspondentes na documentação
- [x] Minhas alterações não geram novos alertas

2023-04-11 13:51 UTC, diego3g requested changes

2023-04-11 13:51 UTC, diego3g commented on apps/server/src/clerk/clerk.guard.ts
> +    const user = await this.clerkService.authenticateUser(authToken)
Olhando pela documentação não ficou claro se esse método aqui é o método ideal pra validar a autenticação do usuário, ou estou errado? Você encontrou isso em algum local?

Olhando pros exemplos da SDK de Node.js com Express encontrei que lá usam o método `authenticateRequest`, chegou a dar uma olhada? (https://github.com/clerkinc/javascript/blob/main/packages/sdk-node/src/authenticateRequest.ts#L23).

Minha preocupação: o Clerk precisa fazer uma requisição HTTP a cada verificação do usuário ou será que tem uma forma da gente validar o token JWT sem precisar ficar batendo toda hora na API do Clerk?

Como o Clerk oferece um middleware nativo para Express e o Nest por padrão usa Express por baixo dos panos, podemos talvez usar o próprio middleware do Express? 

Docs de Middleware do Nest: https://docs.nestjs.com/middleware#applying-middleware
Middleware do Clerk: https://github.com/clerkinc/javascript/blob/main/packages/sdk-node/examples/express/src/router-level-middelware.ts#L37

2023-04-11 13:51 UTC, diego3g commented on apps/server/src/clerk/requestInterface.dto.ts
> +export interface RequestWithUser extends Response {
Aqui acho que não é `Response`, certo? Além disso, vi que o Clerk tem umas tipagens internas como o `RequireAuthProp` que estende a requisição e adiciona as informações de autenticação, será que conseguimos usar? https://github.com/clerkinc/javascript/blob/main/packages/sdk-node/examples/express/src/router-level-middelware.ts#L38

2023-04-11 23:03 UTC, eletroswing commented on apps/server/src/clerk/clerk.guard.ts
> +    const user = await this.clerkService.authenticateUser(authToken)
mas nesse caso então iriamos substituir o decorator UseGuards para utilizar o middleware do próprio nestjs, correto?

2023-04-11 23:03 UTC, eletroswing commented on apps/server/src/clerk/requestInterface.dto.ts
> +export interface RequestWithUser extends Response {
irei realizar as alterações sugeridas!

2023-04-12 15:56 UTC, diego3g commented on apps/server/src/clerk/clerk.guard.ts
> +    const user = await this.clerkService.authenticateUser(authToken)
Na minha visão, o mais interessante seria continuar com o guard, mas garantir que estamos usando o método correto de validar a autenticação do usuário que pode ser o `authenticateUser` ou não. 

Meu medo é justamente esse método fazer uma requisição HTTP toda vez que precisarmos validar que o usuário está autenticado se tornando muito pesado. 

Se você conseguir validar que isso não acontece, seria ótimo, ou ver se outros métodos como o `authenticateRequest` podem ser úteis.

2023-04-12 16:57 UTC, eletroswing commented on apps/server/src/clerk/requestInterface.dto.ts
> +export interface RequestWithUser extends Response {
@diego3g  por algum motivo o `ClerkExpressRequireAuth` retorna um 500 na api, e só loga unauthenticated no console, e não consigo pegar ou manipular esse erro nem com try-catch e nem a opçao on error, estou pensando em usar `ClerkExpressWithAuth` e mais um outro middleware que verifica se req.auth não é undefined para ai retornar o erro, mas não tenho certeza se é a melhor forma de fazer isso...

2023-04-12 17:29 UTC, diego3g commented on apps/server/src/clerk/requestInterface.dto.ts
> +export interface RequestWithUser extends Response {
@eletroswing Pode ser... eu realmente não testei pra dizer se é o melhor formato ou não.

2023-04-12 18:35 UTC, eletroswing commented on apps/server/src/clerk/requestInterface.dto.ts
> +export interface RequestWithUser extends Response {
realizei o commit(acredito que a verificação vindo por parte do middleware não execute novas requisições)

2023-04-12 18:47 UTC, diego3g commented on apps/server/src/clerk/clerk.middleware.ts
> +export class ClerkMiddleware implements NestMiddleware {
Não podemos usar um guard aqui ao invés desse middleware?

Minha preocupação: teremos rotas públicas e privadas, como vamos diferenciar de maneira simples?

2023-04-12 18:47 UTC, diego3g commented on apps/server/src/clerk/clerk.middleware.ts
> +  async use(req: RequireAuthProp<Request>, res: Response, next: NextFunction) {
Quais dados tudo vem dentro de `req.auth`?

2023-04-12 22:16 UTC, luizeboli commented on apps/server/src/clerk/requestInterface.dto.ts
> +export interface RequestWithUser extends Response {
Se me permitem uma contribuição, o Clerk precisa da chave publica JWT pra validar o token, e essa chave é obtida através de um request. Pela documentação há um cache para obter a chave apenas na primeira vez, mas não tem muita informação sobre.

Importante notar que para ambientes Edge talvez seja necessário fazer essa validação de forma manual.

Referências:
https://clerk.com/docs/reference/node/networkless-token-verification
https://clerk.com/docs/request-authentication/validate-session-tokens

2023-04-12 22:45 UTC, eletroswing commented on apps/server/src/clerk/requestInterface.dto.ts
> +export interface RequestWithUser extends Response {
olhando a documentação do middleware: 
> O token de sessão JWT do funcionário pode ser verificado sem rede usando a chave de verificação JWT.
  Por padrão, o Clerk usará nosso ponto de extremidade JWKs conhecido para buscar e armazenar em cache a chave para qualquer verificação de token subsequente. Se você usar a CLERK_JWT_KEYvariável de ambiente ou a opção jwtKey para fornecer a chave, o Clerk irá pegá-la e fazer a verificação sem rede para tokens de sessão usando-a.
  Para obter mais informações, consulte Verificação de token sem rede .

dessa forma, é so adicionar uma chave jwt no .env para tornar uma verificação sem rede

2023-04-12 22:53 UTC, eletroswing commented on apps/server/src/clerk/clerk.middleware.ts
> +  async use(req: RequireAuthProp<Request>, res: Response, next: NextFunction) {
os dados são o padrão e já vem com seus tipos direto do clerk, sendo eles: 
```
data: {
    "sessionClaims": null,
    "sessionId": null,
    "session": null,
    "userId": null,
    "user": null,
    "actor": null,
    "orgId": null,
    "orgRole": null,
    "orgSlug": null,
    "organization": null,
    "claims": null
}
```

2023-04-12 23:57 UTC, luizeboli commented on apps/server/src/main.ts
> +    ClerkExpressWithAuth({ jwtKey: process.env.CLERK_JWT_KEY || randomUUID() }),
Não é possível usar um randomUUID, essa chave precisa ser a mesma que está no dashboard da aplicação do Clerk. Qualquer outra coisa diferente disso vai quebrar a validação.

2023-04-13 00:02 UTC, luizeboli commented on apps/server/src/clerk/clerk.middleware.ts
> +export class ClerkMiddleware implements NestMiddleware {
Talvez seja interessante ter os dois, um middleware e um guard. Isso porque creio que será necessário relacionar no banco as entidades com o id do usuário owner, não?

O middleware `ClerkExpressWithAuth` faria a injeção do objeto `auth`, enquanto o papel do guard seria checar se esse objeto existe no request, e então liberar a rota.

Oq acha?

2023-04-13 00:15 UTC, eletroswing commented on apps/server/src/main.ts
> +    ClerkExpressWithAuth({ jwtKey: process.env.CLERK_JWT_KEY || randomUUID() }),
Essa chave é uma string que vem direto do .env, so botei essa option pra aplicação não quebrar devido a falta de uma chave, mas em sumo, pode ser qualquer string(referindo a api):
> O token de sessão JWT do funcionário pode ser verificado sem rede usando a chave de verificação JWT.
Por padrão, o Clerk usará nosso ponto de extremidade JWKs conhecido para buscar e armazenar em cache a chave para qualquer verificação de token subsequente. Se você usar a CLERK_JWT_KEY va
riável de ambiente ou a opção jwtKey para fornecer a chave, o Clerk irá pegá-la e fazer a verificação sem rede para tokens de sessão usando-a.
Para obter mais informações, consulte Verificação de token sem rede .

**Documentação**
![Capturar](https://user-images.githubusercontent.com/90343384/231613033-544531d3-6fa7-4f61-9e63-83378e49383f.PNG)

2023-04-13 00:19 UTC, eletroswing commented on apps/server/src/clerk/clerk.middleware.ts
> +export class ClerkMiddleware implements NestMiddleware {
foi exatamente o que eu fiz nesse pull @luizeboli , o middleware global, e o guarda, que so checa a existência do objeto auth.

2023-04-13 00:25 UTC, luizeboli commented on apps/server/src/main.ts
> +    ClerkExpressWithAuth({ jwtKey: process.env.CLERK_JWT_KEY || randomUUID() }),
Sim, é que se essa env não existir, vai usar uma string aleatória, e dessa forma não vai conseguir validar o token. Eu comentei porque isso pode acabar mascarando um possível problema que seria a falta do env.

2023-04-13 00:28 UTC, eletroswing commented on apps/server/src/main.ts
> +    ClerkExpressWithAuth({ jwtKey: process.env.CLERK_JWT_KEY || randomUUID() }),
Sugere a substituição do Ransom Crypto por uma string hardcode?

2023-04-13 00:32 UTC, eletroswing commented on apps/server/src/main.ts
> +    ClerkExpressWithAuth({ jwtKey: process.env.CLERK_JWT_KEY || randomUUID() }),
@luizeboli realizei as alterações e deixei a string hardcode.

2023-04-13 00:38 UTC, diego3g commented on apps/server/src/clerk/requestInterface.dto.ts
> +export interface RequestWithUser extends Response {
Melhor ainda

2023-04-13 00:40 UTC, diego3g commented on apps/server/src/main.ts
> +    ClerkExpressWithAuth({ jwtKey: process.env.CLERK_JWT_KEY || randomUUID() }),
O melhor seria realmente disparar um erro se a chave não existir, tu pode ver se ta vazia e dar um throw new Error

2023-04-15 21:29 UTC, closed without merging